### ISSUE TITLE
How-to: Test based on other field ?

### ISSUE THREAD

**Issue by ghost** [MaxKostenko/es6-form-validation#1]
Hi,

first of all: very good work you've done 👍 

One question: how to test a field only if one other is filled ? For example: if I have two field to define a new password (so one field for the new password and the second for the confirmation of the new password), how to make the confirmation password field as "require" only if the new password field is filled ?

I mean: make validations based on the validity (and non-empty) of one other.

Regards

**Comment by MaxKostenko** [comment]
Lib doesn't have standard mechanism for it. But you can create custom validator for it. I have appended code example to "examples/12 - Custom validator.html"
